### ISSUE TITLE
v3.0.0 Release Checklist

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#214]
- [ ] Set bylines + date in each book
- [ ] Review and finalize the change description in CHANGELOG.md.
- [ ] Tag last commit with "v3.0.0" label.

**Comment by hollasch** [comment]
Forked into independent issues: #302, #303, #304
