### ISSUE TITLE
Validate Book 2 progression for milestone alpha.2

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#779]
After the messy merge of `dev-patch` (v3.2.2) into `dev-minor` and all of the work going on in v4, we should run through the book progression before v4 release.

Validate/update rendered images. Make sure that they are PNG format, and sized according to the rendered size specified in the code.

- [x] 2.1: Bouncing spheres
- [x] 2.2: Spheres on checkered ground
- [x] 2.3: Checkered spheres
- [x] 2.5: Earth-mapped sphere
- [x] 2.6: White noise
- [x] 2.7: White noise, blurred
- [x] 2.8: Tiled random patterns
- [x] 2.9: Hashed random texture
- [x] 2.10: Perlin texture with trilinear interpolation
- [x] 2.11: Perlin texture, trilinearly interpolated, smoothed
- [x] 2.12: Perlin texture, higher frequency
- [x] 2.13: Perlin texture, shifted off integer values
- [x] 2.14: Perlin texture with turbulence
- [x] 2.15: Perlin noise, marbled texture
- [x] 2.16: Scene with rectangle light source
- [x] 2.17: Scene with rectangle and sphere light sources
- [x] 2.18: Empty Cornell box
- [x] 2.19: Cornell box with two blocks
- [x] 2.20: Standard Cornell box scene
- [x] 2.21: Cornell box with blocks of smoke
- [x] 2.22: Final scene

**Comment by hollasch** [comment]
Done.
