### ISSUE TITLE
Validate Book 3 progression for milestone v4.0.0

### ISSUE THREAD

**Issue by hollasch** [RayTracing/raytracing.github.io#863]
Run through the book progression before v4 release.

Validate/update rendered images. Make sure that they are PNG format, and sized according to the rendered size specified in the code.

- [x] 3.1: Cornell box, no stratification
- [x] 3.2: Cornell box, with stratification (*see note below*)
- [x] 3.3: Cornell box, refactored
- [x] 3.4: Cornell box, with imperfect PDF
- [x] 3.5: Cornell box, with uniform hemispherical sampling (_new render_)
- [x] 3.6: Cornell box, with orthonormal basis scatter function
- [x] 3.7: Cornell box, sampling only the light, 10 samples per pixel
- [x] 3.8: Cornell box, light emitted only in the downward direction
- [x] 3.9: Cornell box with a cosine density PDF
- [x] 3.10: Cornell box, sampling a hittable light, 10 samples per pixel
- [x] 3.11: Cornell box, mixture density of cosine and light sampling
- [x] 3.12: Cornell box with arbitrary PDF functions
- [x] 3.13: Cornell box with glass sphere, using new PDF functions
- [x] 3.14: Cornell box using a mixture of glass & light PDFs
- [x] 3.15: Cornell box with anti-acne color function

Compare render 3.01 and 3.02. They _should_ be the same. If they have slightly different noise, then the text needs to be slightly altered:
```
You should get exactly the same picture.
```
→
```
You should get the same picture, hopefully with less noise
```

**Comment by hollasch** [comment]
Review #900.
